<div class="section section-numbers-1" id="numbers">
    <div class="container">
        <div class="text-area">
            <div class="title add-animation">
                <h1>404</h1>
                <h2>Whoops!</h2>
                <div class="separator-container">
                    <div class="separator line-separator">∎</div>
                </div>
                <p>Seems like you are trying to reach is not there!</p>
            </div>
        </div>
        <div class="clearfix"></div>
        
    </div>
</div>
